language: node_js

node_js:
  - 10
  - 12
  - 14

before_install:
  - npm install -g codecov
install:
  - npm i

cache: 
  npm: true

script:
  - npm run test
  - npm run report-coverage