dist: xenial
language: node_js

node_js:
  - 10
  - 12
  - 14

install:
  - npm i

cache: 
  npm: true

jobs:
  include:
    - stage: test_cov
      script: 
      - chmod +x ./scripts/test_cov.sh
      - sh ./scripts/test_cov.sh