dist: xenial
language: node_js

node_js:
  - 10
  - 12
  - 14

install:
  - npm i

cache: 
  npm: true

jobs:
  include:
    - stage: test_cov
      before_script:
        - chmod +x ./scripts/*.sh
      script: 
        - sh ./scripts/test_cov.sh