language: node_js

node_js:
  - 10
  - 12
  - 14

before_install:
  - npm install -g codecov
install:
  - npm i

cache: 
  npm: true

script:
  - npm run test:cov
  - istanbul cover ./node_modules/.bin/mocha test/*.spec.js test/**/*.sepc.js --reporter lcovonly -- -R spec
  - codecov